#!/usr/bin/env bash
# Writes ios/Runner/GoogleService-Info.plist + lib/firebase_options.dart
# for project consulta-cnpj-1196c without requiring the Ruby xcodeproj gem.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

export PATH="${PATH}:${HOME}/.pub-cache/bin:/opt/homebrew/bin"

PROJECT_ID="consulta-cnpj-1196c"
ANDROID_APP_ID="1:894074953486:android:c5f731d097e0c0e777c15f"
IOS_BUNDLE_ID="br.com.cgy.consultaCnpjEmpresas"

if ! command -v firebase >/dev/null 2>&1; then
  echo "firebase CLI missing. Install: brew install firebase-cli"
  exit 1
fi

if ! firebase projects:list >/dev/null 2>&1; then
  echo "Not logged in. Run: firebase login"
  exit 1
fi

echo "Fetching iOS app id for bundle $IOS_BUNDLE_ID..."
IOS_APP_ID="$(firebase apps:list --project="$PROJECT_ID" --json \
  | python3 -c "
import json,sys
data=json.load(sys.stdin)
apps=data.get('result', data) if isinstance(data, dict) else data
if isinstance(apps, dict) and 'result' in apps:
  apps=apps['result']
for a in apps:
  platform=(a.get('platform') or a.get('appId','')).upper()
  app_id=a.get('appId') or ''
  if 'IOS' in str(a.get('platform','')).upper() or ':ios:' in app_id:
    print(app_id)
    break
")"

if [[ -z "${IOS_APP_ID:-}" ]]; then
  echo "No iOS app found. Creating..."
  firebase apps:create IOS "CNPJ Consulta iOS" \
    --project="$PROJECT_ID" \
    --bundle-id="$IOS_BUNDLE_ID"
  IOS_APP_ID="$(firebase apps:list --project="$PROJECT_ID" --json \
    | python3 -c "
import json,sys
data=json.load(sys.stdin)
apps=data.get('result', data) if isinstance(data, dict) else data
if isinstance(apps, dict) and 'result' in apps:
  apps=apps['result']
for a in apps:
  app_id=a.get('appId') or ''
  if ':ios:' in app_id:
    print(app_id)
    break
")"
fi

echo "iOS app: $IOS_APP_ID"
firebase apps:sdkconfig IOS "$IOS_APP_ID" --project="$PROJECT_ID" \
  > ios/Runner/GoogleService-Info.plist

# Parse keys for firebase_options.dart
eval "$(python3 - <<'PY'
import plistlib, pathlib, re, json
plist = plistlib.loads(pathlib.Path("ios/Runner/GoogleService-Info.plist").read_bytes())
android = json.loads(pathlib.Path("android/app/google-services.json").read_text())
client = android["client"][0]
android_opts = {
  "apiKey": client["api_key"][0]["current_key"],
  "appId": client["client_info"]["mobilesdk_app_id"],
  "messagingSenderId": android["project_info"]["project_number"],
  "projectId": android["project_info"]["project_id"],
  "storageBucket": android["project_info"]["storage_bucket"],
}
ios_opts = {
  "apiKey": plist["API_KEY"],
  "appId": plist["GOOGLE_APP_ID"],
  "messagingSenderId": plist["GCM_SENDER_ID"],
  "projectId": plist["PROJECT_ID"],
  "storageBucket": plist["STORAGE_BUCKET"],
  "iosBundleId": plist["BUNDLE_ID"],
}
def esc(s): return s.replace("\\", "\\\\").replace("'", "\\'")
print(f"ANDROID_API_KEY='{esc(android_opts['apiKey'])}'")
print(f"ANDROID_APP='{esc(android_opts['appId'])}'")
print(f"ANDROID_SENDER='{esc(android_opts['messagingSenderId'])}'")
print(f"ANDROID_PROJECT='{esc(android_opts['projectId'])}'")
print(f"ANDROID_BUCKET='{esc(android_opts['storageBucket'])}'")
print(f"IOS_API_KEY='{esc(ios_opts['apiKey'])}'")
print(f"IOS_APP='{esc(ios_opts['appId'])}'")
print(f"IOS_SENDER='{esc(ios_opts['messagingSenderId'])}'")
print(f"IOS_PROJECT='{esc(ios_opts['projectId'])}'")
print(f"IOS_BUCKET='{esc(ios_opts['storageBucket'])}'")
print(f"IOS_BUNDLE='{esc(ios_opts['iosBundleId'])}'")
PY
)"

cat > lib/firebase_options.dart <<EOF
// File generated by scripts/configure_firebase.sh
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '$ANDROID_API_KEY',
    appId: '$ANDROID_APP',
    messagingSenderId: '$ANDROID_SENDER',
    projectId: '$ANDROID_PROJECT',
    storageBucket: '$ANDROID_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '$IOS_API_KEY',
    appId: '$IOS_APP',
    messagingSenderId: '$IOS_SENDER',
    projectId: '$IOS_PROJECT',
    storageBucket: '$IOS_BUCKET',
    iosBundleId: '$IOS_BUNDLE',
  );
}
EOF

# Drop placeholder guard if still present in FirebaseService
if grep -q 'isIosAppIdPending' lib/firebase_options.dart 2>/dev/null; then
  true
fi

echo ""
echo "Updated:"
echo "  ios/Runner/GoogleService-Info.plist"
echo "  lib/firebase_options.dart"
echo ""
echo "Next (manual): Firebase Console → Cloud Messaging → upload APNs Auth Key (.p8)"
echo "See docs/IOS_SETUP.md"
